config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'

  resources :categories, only: [:index] do
    resources :articles
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :articles
  has_many :categories, through: :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout proc { false if request.xhr? }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :set_category

  def index
    @articles = Article.where(category: @category)
  end

  def show

  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to category_articles_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      render :show
    else
      render :edit
    end
  end


  def destroy
    @article.destroy
    redirect_to category_articles
  end

  private
    def article_params
      params.require(:article).permit(:name, :description, :price, :category_id, :user_id )
    end

    def set_article
      @article = Article.find(params[:id])
    end

    def set_category
      @category = Category.find(params[:category_id])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_for [@category, @article] do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name, size: "50" %><br>

  <%= f.label :description %>:
  <%= f.text_area :description, size: "30x10" %><br>

  <%= f.label :price %>:
  <%= f.text_field :price %><br>

  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
</h1> This is the edit page! <h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1><%= @category.name %> </h1>
<%= button_to 'Make a new listing!', new_category_article_path(@category, @article), :method => "get" %>
<div class="all_articles">
  <% @articles.each do |article| %>
    <p><%= link_to article.name, [@category, article] %></p>
  <% end %>
</div>

app/views/articles/new.html.erb
</h1> This is the new page! <h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1> <%= @article.name %> </h3>

<p> <%= @article.description %> <p>
<p><%= @article.price %> <p>


<%= link_to 'Edit', edit_category_article_path(@category, @article) %>

app/views/categories/index.html.erb
<h1>Hello World!</h1>
<div class="all_categories">
  <% @categories.each do |category| %>
    <p><%= link_to category.name, category_articles_path(category) %></p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CraigslistJr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <%= link_to "HOME", categories_path %>
</nav>
<%= yield %>

</body>
</html>